### ISSUE TITLE
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range

### ISSUE THREAD

**Issue by Dook1** [ibilux/MobyDroid#2]
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 20
        at java.lang.String.substring(Unknown Source)
        at au.a(Unknown Source)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at au.b(Unknown Source)
        at au.<init>(Unknown Source)
        at com.hq.mobydroid.MobyDroid.main(Unknown Source)

```

**Comment by kinoegit** [comment]
same here:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 20
        at java.lang.String.substring(String.java:1963)
        at au.a(Unknown Source)
        at java.util.HashMap$Values.forEach(HashMap.java:981)
        at au.b(Unknown Source)
        at au.<init>(Unknown Source)
        at com.hq.mobydroid.MobyDroid.main(Unknown Source)

**Comment by ibilux** [comment]
Has been fixed in v0.2. you can download jar file from here:

https://github.com/ibilux/MobyDroid/releases/tag/v0.2

**Comment by kinoegit** [comment]
thanks! running smoothly. nice peace of work. 
if you'd like me to translate mobydroid into german give me a go-ahead

**Comment by ibilux** [comment]
@kinoegit yeah sure. but let me finish making a translation file first.
so this ticket is closed.
